import assert from 'node:assert/strict'

/** Parcours réel de l'éditeur, dans le workspace de démonstration temporaire du test UI. */
export async function checkEditor({ page, context, base, project }) {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto(`${base}/p/${project.id}/board`)
  await page.getByRole('button', { name: 'Ouvrir le panneau', exact: true }).click()
  const panel = page.locator('[data-panel="workspace"]')
  const showTree = panel.getByRole('button', { name: "Afficher l'arborescence", exact: true })
  if (await showTree.count()) await showTree.click()
  const endpoint = `${base}/api/projects/${project.id}/file`
  const read = async (path = 'package.json') => (await context.request.get(endpoint + '?path=' + encodeURIComponent(path))).json()
  const original = await read()
  const makeContent = (value) => JSON.stringify({ ...JSON.parse(original.content), uiCheck: value }, null, 2) + '\n'
  const draftA = makeContent('a'), draftB = makeContent('b'), draftC = makeContent('c')
  const code = panel.locator('.cm-content')
  const save = panel.getByRole('button', { name: 'Enregistrer', exact: true })
  const waitText = (text) => page.waitForFunction((text) => document.querySelector('[data-panel="workspace"] .cm-content')?.textContent.includes(text), text)
  const waitClean = () => panel.getByRole('status').filter({ hasText: 'À jour' }).waitFor()
  const treeFile = (path) => panel.getByRole('button', { name: path, exact: true }).first()

  await treeFile('package.json').click()
  await code.fill(draftA)
  await treeFile('index.html').click()
  await panel.getByRole('button', { name: 'Ouvrir package.json, non enregistré', exact: true }).click()
  await waitText('"uiCheck": "a"')
  await panel.getByRole('button', { name: 'Git', exact: true }).click()
  await panel.getByRole('button', { name: 'Fichiers', exact: true }).click()
  await waitText('"uiCheck": "a"')
  await panel.getByRole('button', { name: 'Fermer package.json', exact: true }).click()
  const recovery = panel.locator('details').filter({ hasText: 'Brouillons conservés' })
  await recovery.getByRole('button', { name: 'package.json', exact: true }).waitFor()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => localStorage.setItem('sillage.panelTree', '1'))
  await page.reload()
  await panel.getByRole('button', { name: 'Brouillons conservés (1)', exact: true }).click()
  await recovery.getByRole('button', { name: 'package.json', exact: true }).click()
  await waitText('"uiCheck": "a"')
  await page.setViewportSize({ width: 1440, height: 900 })
  assert.equal((await read()).content, original.content, 'A recovered draft must not write to disk')

  await page.route(endpoint, async (route) => {
    if (route.request().method() === 'PUT') await route.fulfill({ status: 503, json: { error: { code: 'ui_write_failed', message: 'Écriture indisponible pour le test.' } } })
    else await route.continue()
  })
  await save.click()
  await panel.getByRole('alert').filter({ hasText: 'Ton brouillon est conservé.' }).waitFor()
  await waitText('"uiCheck": "a"')
  await page.unroute(endpoint)

  let release, sent, writes = 0
  const gate = new Promise((resolve) => { release = resolve })
  const intercepted = new Promise((resolve) => { sent = resolve })
  await page.route(endpoint, async (route) => {
    if (route.request().method() === 'PUT') { writes++; sent(); await gate }
    await route.continue()
  })
  await panel.getByRole('button', { name: 'Réessayer', exact: true }).click()
  await intercepted
  await code.fill(draftB)
  await panel.getByRole('button', { name: 'Fermer le panneau', exact: true }).click()
  await panel.waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: 'Ouvrir le panneau', exact: true }).click()
  await waitText('"uiCheck": "b"')
  assert.equal(await panel.getByRole('button', { name: 'Enregistrement…', exact: true }).isDisabled(), true)
  await code.click()
  await page.keyboard.press('Control+s')
  assert.equal(writes, 1, 'A pending save cannot be sent twice after remounting')
  release()
  await save.waitFor()
  await page.waitForFunction(() => ![...document.querySelectorAll('[data-panel="workspace"] button')].find((node) => node.textContent === 'Enregistrer')?.disabled)
  await page.unroute(endpoint)
  assert.equal((await read()).content, draftA)
  await waitText('"uiCheck": "b"')
  await save.click()
  await waitClean()
  assert.equal((await read()).content, draftB)
  await code.fill(draftC)
  await code.fill(draftB)
  await waitClean()
  assert.equal(await save.isDisabled(), true, 'Dirty status compares against the latest saved content')
  console.log('OK : brouillons de fichiers après changement d’onglet, fermeture et rechargement ; erreurs et sauvegardes concurrentes.')

  const external = makeContent('external')
  await code.fill(draftC)
  let disk = await read()
  assert.ok((await context.request.put(endpoint, { data: { path: 'package.json', content: external, fingerprint: disk.fingerprint } })).ok())
  await save.click()
  const conflict = panel.getByRole('alert').filter({ hasText: 'Le fichier a changé sur le disque.' })
  await conflict.waitFor()
  await waitText('"uiCheck": "c"')
  page.once('dialog', dialog => dialog.dismiss())
  await panel.getByRole('button', { name: 'Utiliser la version du disque', exact: true }).click()
  await waitText('"uiCheck": "c"')
  page.once('dialog', dialog => dialog.accept())
  await panel.getByRole('button', { name: 'Utiliser la version du disque', exact: true }).click()
  await waitText('"uiCheck": "external"')
  await waitClean()
  await conflict.waitFor({ state: 'hidden' })

  await code.fill(draftC)
  disk = await read()
  assert.ok((await context.request.put(endpoint, { data: { path: 'package.json', content: makeContent('external-again'), fingerprint: disk.fingerprint } })).ok())
  await save.click()
  await conflict.waitFor()
  page.once('dialog', dialog => dialog.accept())
  await panel.getByRole('button', { name: 'Remplacer par mon brouillon', exact: true }).click()
  await waitClean()
  assert.equal((await read()).content, draftC)

  // Une relecture lente ne doit pas effacer le texte tapé après son déclenchement.
  await code.fill(draftA)
  let readRelease, readSent
  const readGate = new Promise((resolve) => { readRelease = resolve })
  const readIntercepted = new Promise((resolve) => { readSent = resolve })
  await page.route(endpoint + '?path=package.json', async (route) => { readSent(); await readGate; await route.continue() })
  page.once('dialog', dialog => dialog.accept())
  await panel.getByRole('button', { name: 'Abandonner les modifications', exact: true }).click()
  await readIntercepted
  await code.fill(draftB)
  readRelease()
  await panel.getByRole('status').filter({ hasText: 'Non enregistré' }).waitFor()
  await waitText('"uiCheck": "b"')
  await page.unroute(endpoint + '?path=package.json')
  page.once('dialog', dialog => dialog.accept())
  await panel.getByRole('button', { name: 'Abandonner les modifications', exact: true }).click()
  await waitText('"uiCheck": "c"')
  await waitClean()
  console.log('OK : conflit réel avec le disque, rechargement effectif, choix explicite du brouillon et relecture lente sans perte.')

  // Quand le navigateur refuse le stockage, l'interface doit annoncer sa vraie limite.
  await page.evaluate(() => {
    window.uiOriginalSetItem = Storage.prototype.setItem
    Storage.prototype.setItem = function (key, value) {
      if (key.startsWith('sillage.fileDraft:')) throw new DOMException('QuotaExceededError')
      return window.uiOriginalSetItem.call(this, key, value)
    }
  })
  await code.fill(draftA)
  await panel.getByText('Stockage indisponible : brouillon gardé en mémoire jusqu’à la fermeture de la page.', { exact: true }).waitFor()
  await page.evaluate(() => { Storage.prototype.setItem = window.uiOriginalSetItem; delete window.uiOriginalSetItem })
  await code.fill(draftB)
  await panel.getByText('Brouillon conservé dans cet onglet, pas encore enregistré sur le disque.', { exact: true }).waitFor()
  await code.fill(draftC)
  await waitClean()

  if (await showTree.count()) await showTree.click()
  const readEndpoint = endpoint + '?path=vite.config.ts'
  await page.route(readEndpoint, route => route.fulfill({ status: 500, json: { error: { code: 'ui_read_failed', message: 'Lecture indisponible pour le test.' } } }))
  await treeFile('vite.config.ts').click()
  await panel.getByRole('alert').filter({ hasText: 'Lecture indisponible pour le test.' }).waitFor()
  await page.unroute(readEndpoint)
  await panel.getByRole('button', { name: 'Réessayer', exact: true }).click()
  await waitText('defineConfig')
  await waitClean()
  await page.setViewportSize({ width: 390, height: 844 })
  assert.equal(await code.isVisible(), false, 'The editor behind the mobile file tree is hidden from the keyboard path')
  await panel.getByRole('button', { name: "Masquer l'arborescence", exact: true }).click()
  await code.waitFor()
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Editor overflow at ${width}px`)
    const box = await save.boundingBox()
    assert.ok(box.x >= 0 && box.x + box.width <= width + 1, `Save button outside the viewport at ${width}px`)
    if (width < 768) assert.ok(box.height >= 44)
  }
  await panel.getByRole('button', { name: 'Fermer le panneau', exact: true }).click()
  await panel.waitFor({ state: 'hidden' })
  console.log('OK : reprise après erreur de lecture, stockage indisponible signalé, commandes de l’éditeur accessibles sur mobile.')
}
